{
 "title": "kraken_磁盘缓存 & Peer同步文件大小",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Agent磁盘缓存__Node维度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(disk_usage{job=\"kraken-agent\", exported_job=\"cache\"} * on(pod) group_left(node) (sum(kube_pod_info{job=\"kube-state-metrics\", node=~\"$node\",namespace=\"kraken\"}) by (node, pod) == 1)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Origin磁盘缓存__Pod维度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_usage{job=\"kraken-origin\", exported_job=\"cache\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Agent被docker下载的文件大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kraken_docker_registry_reader_bytes[1m]) * on(pod) group_left(node) (sum(kube_pod_info{job=\"kube-state-metrics\", node=~\"$node\",namespace=\"kraken\"}) by (node, pod) == 1)) by (node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Peer__P2P__被下载的文件大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kraken_p2p_message_transfer_bytes[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Peer__被下载的次数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kraken_p2p_message_transfer_count[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Origin__下载Blob的大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kraken_download_remote_blob_bytes[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Origin__下载Blob的次数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kraken_download_remote_blob_count[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Piece__写入冲突次数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kraken_write_piece_failed_count[1m]) * on(pod) group_left(node) (sum(kube_pod_info{job=\"kube-state-metrics\", node=~\"$node\",namespace=\"kraken\"}) by (node, pod) == 1))by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Origin__整体流入带宽",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{namespace=~\"kraken\", pod=~\"kraken-origin.*\"}[$__rate_interval])) by (pod) * 8)",
     "legendFormat": "total"
    }
   ]
  }
 ]
}