{
 "title": "Horizon - SLO",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "env", "query": "test,online" }
  ]
 },
 "panels": [
  {
   "title": "API",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_request:availability{verb=\"all\",range=\"1h\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_request:availability{verb=\"all\",range=\"1d\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_request:availability{verb=\"all\",range=\"30d\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Build-Git",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_git:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_git:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_git:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Build-Git RT",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_git_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_git_rt:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_git_rt:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Build-Image",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_image:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_image:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_git:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Build-Image RT",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_image_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_image_rt:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_image_rt:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Deploy",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_deploy:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_deploy:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_deploy:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Deploy RT",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_deploy_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_deploy_rt:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_deploy_rt:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Degree of resource satisfaction",
   "type": "table",
   "description": "Percentage of Pods that get resources and are successfully scheduled",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_resources_meet:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_resources_meet:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_resources_meet:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  {
   "title": "Pod Create RT",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "horizon_container_create_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "1h"
    },
    {
     "expr": "horizon_container_create_rt:availability{range=\"1d\",env=\"$env\"}",
     "legendFormat": "1d"
    },
    {
     "expr": "horizon_container_create_rt:availability{range=\"30d\",env=\"$env\"}",
     "legendFormat": "30d"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Availability",
   "type": "graph",
   "description": "How many percent of requests (both read and write) \n have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_request:availability{verb=\"all\",range=\"1h\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "ErrorBudget",
   "type": "graph",
   "description": "How much error budget is left looking at availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_request:availability{verb=\"all\",range=\"1h\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "Read Availability(RT : 1s)",
   "type": "graph",
   "description": "How many percent of read requests (LIST,GET) have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_request:availability{verb=\"read\",range=\"1h\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "Read SLI - Requests",
   "type": "graph",
   "description": "How many read requests (LIST,GET) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(horizon_request_total{verb=~\"|GET\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Read SLI - Errors",
   "type": "graph",
   "description": "How many percent of read requests (LIST,GET) per second are returned with errors (5xx)?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (rate(horizon_request_total{verb=~\"GET\",code=~\"5..\"}[5m])) / \nsum by (handler) (rate(horizon_request_total{verb=~\"GET\"}[5m]))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Read SLI - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for reading (LIST|GET) a given resource?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, handler) (rate(horizon_request_duration_seconds_bucket{verb=~\"GET\"}[5m]))) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Write Availability(RT : 5s)",
   "type": "graph",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_request:availability{verb=\"write\",range=\"1h\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "Write SLI - Requests",
   "type": "graph",
   "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(horizon_request_total{verb=~\"POST|PUT|DELETE\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Write SLI - Errors",
   "type": "graph",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) per second are returned with errors (5xx)?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (rate(horizon_request_total{verb=~\"POST|PUT|DELETE\",code=~\"5..\"}[5m])) / \nsum by (handler) (rate(horizon_request_total{verb=~\"POST|PUT|DELETE\"}[5m]))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write SLI - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for writing (POST|PUT|PATCH|DELETE) a given resource?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, handler) (rate(horizon_request_duration_seconds_bucket{verb=~\"POST|PUT|DELETE\"}[5m]))) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Build - Git", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Availability",
   "type": "graph",
   "description": "How many percent of git pull have been executed successfully?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_git:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "ErrorBudget",
   "type": "graph",
   "description": "How much error budget is left looking at availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_git:availability{range=\"1h\",env=\"$env\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "RT Availability (RT : 30s)",
   "type": "graph",
   "description": "How many percent of git pull have been executed successfully in less than $git_rt seconds?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_git_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "RT ErrorBudget",
   "type": "graph",
   "description": "How much error budget is left looking at availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_git_rt:availability{range=\"1h\",env=\"$env\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Build - Image", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Availability",
   "type": "graph",
   "description": "How many percent of image build & push have been executed successfully?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_image:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "ErrorBudget",
   "type": "graph",
   "description": "How much error budget is left looking at availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_image:availability{range=\"1h\",env=\"$env\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "RT Availability (RT : 300s)",
   "type": "graph",
   "description": "How many percent of image build & push have been executed successfully in less than $image_rt seconds?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_image_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "RT ErrorBudget",
   "type": "graph",
   "description": "How much error budget is left looking at availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_image_rt:availability{range=\"1h\",env=\"$env\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Deploy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Availability",
   "type": "graph",
   "description": "How many percent of deploy have been executed successfully?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_deploy:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "ErrorBudget",
   "type": "graph",
   "description": "How much error budget is left looking at availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_deploy:availability{range=\"1h\",env=\"$env\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "RT Availability (RT : 60s)",
   "type": "graph",
   "description": "How many percent of deploy have been executed successfully in less than $deploy_rt seconds?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_deploy_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "RT ErrorBudget",
   "type": "graph",
   "description": "How much error budget is left looking at availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_deploy_rt:availability{range=\"1h\",env=\"$env\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "Degree of resource satisfaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_resources_meet:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "ErrorBudget",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_resources_meet:availability{env=\"$env\",range=\"1h\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Pod Create RT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "RT Availability (RT : 60s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "horizon_container_create_rt:availability{range=\"1h\",env=\"$env\"}",
     "legendFormat": "availability"
    },
    { "expr": "0.95", "legendFormat": "baseline" }
   ]
  },
  {
   "title": "RT ErrorBudget",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / (1 - 0.95) * (horizon_container_create_rt:availability{env=\"$env\",range=\"1h\"} - 0.95)",
     "legendFormat": "errorbudget"
    }
   ]
  }
 ]
}