apiVersion: v1
kind: Service
metadata:
  name: {{ template "horizon.core" . }}-mcp
  labels:
{{ include "horizon.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.core.mcpService.port }}
      targetPort: {{ .Values.config.mcpConfig.port }}
  selector:
{{ include "horizon.matchLabels" . | indent 4 }}
    component: core
